[phases.setup]
nixPkgs = ["dotnetCorePackages.sdk_9_0"]

[phases.build]
cmds = ["dotnet publish AssignmentSystem.API/AssignmentSystem.API.csproj -c Release -o out"]

[start]
cmd = "dotnet out/AssignmentSystem.API.dll"