[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = ["dotnet publish AssignmentSystem.API/AssignmentSystem.API.csproj -c Release -o out"]

[start]
cmd = "dotnet out/AssignmentSystem.API.dll"